# Generated by Django 5.2.10 on 2026-01-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('protocolo', models.CharField(max_length=30, unique=True, verbose_name='Protocolo')),
                ('status', models.CharField(choices=[('cadastrada', 'Cadastrada'), ('em_analise', 'Em Análise'), ('em_execucao', 'Em Execução'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='Cadastrada', max_length=20, verbose_name='Situação')),
                ('urgencia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='baixa', max_length=20, verbose_name='Nível de Urgência')),
                ('categoria', models.CharField(choices=[('pavimentacao', 'Pavimentação e Tapa-buracos'), ('iluminacao', 'Iluminação Pública'), ('saneamento', 'Saneamento e Drenagem'), ('limpeza', 'Limpeza Urbana e Resíduos'), ('arborizacao', 'Poda de Árvores e Jardins'), ('sinalizacao', 'Trânsito e Sinalização'), ('zoonoses', 'Zoonoses e Animais'), ('fiscalizacao', 'Fiscalização de Obras/Posturas'), ('equipamentos', 'Equipamentos Públicos (Parques/Praças)'), ('outros', 'Outros Assuntos')], default='outros', max_length=50, verbose_name='Categoria')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero_endereco', models.CharField(max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('id_demanda', models.IntegerField(verbose_name='ID da Demanda')),
            ],
        ),
    ]
