# Generated by Django 5.2.10 on 2026-02-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacoes',
            name='nome_vereador',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Nome do Vereador'),
        ),
    ]
