# Generated by Django 5.2.10 on 2026-02-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0002_indicacoes_nome_vereador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacoes',
            name='id_demanda',
            field=models.IntegerField(default=0, verbose_name='ID da Demanda'),
        ),
    ]
