# Generated by Django 5.2.10 on 2026-02-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0003_alter_indicacoes_id_demanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacoes',
            name='protocolo',
        ),
    ]
