# Generated by Django 5.2.10 on 2026-02-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicacoes', '0005_alter_indicacoes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacoes',
            name='status',
            field=models.CharField(choices=[('cadastrada', 'Cadastrada'), ('em_analise', 'Em Análise'), ('em_votacao', 'Em Votação'), ('aprovada', 'Aprovada'), ('nao_aprovada', 'Não Aprovada'), ('em_tramitacao', 'Enviada ao Executivo'), ('em_execucao', 'Em Execução'), ('concluida', 'Concluída')], default='cadastrada', max_length=20, verbose_name='Situação'),
        ),
    ]
